name: nos_analysis
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6.5
  - pip
  - numpy
  - scipy
  - pandas>=1.0.0
  - matplotlib
  - jupyter
  - ipython
  # Put any conda dependencies here
  - dask
  - descartes
  - folium
  - ftfy
  - fuzzywuzzy
  - gensim
  - geojson
  - ipywidgets
  - more-itertools
  - nltk
  - pytorch
  - pyproj
  - scikit-learn
  - seaborn
  - shapely
  - spacy
  - spyder-kernels
  - statsmodels
  - xlrd
  #-pyproj

  - pip:
    # Put any pip dependencies here (and no conda ones anywhere below)
    - nuts_finder
    - pytorch_pretrained_bert==0.6.2
    - spacy
    - sentence-transformers
    - requests
    - boto3
    - Fiona
    #- git+ssh://git@github.com/nestauk/escoe-skill-mismatch.git
    #- git+ssh://git@github.com/nestauk/nuts_finder.git

# link to escoe_skill_mismatch
# link to branch of nuts_finder (ask Joel first because of the name issue)

  # Tooling requirements (don't edit)
    - tqdm
    - pyyaml
    - tables
    - black
    - blackcellmagic
    - pymysql
    - sqlalchemy
    - click
    - Sphinx
    - sphinxcontrib.napoleon
    - coverage
    - awscli
    - flake8
  - python-dotenv>=0.5.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jq
  - pytest
